version: '3.8'

services:
  db:
    image: {{cookiecutter.docker_database_image}}
    container_name: {{cookiecutter.docker_database_image}}
    restart: always
    environment:
      POSTGRES_USER: {{cookiecutter.docker_database_image}}
      POSTGRES_PASSWORD: {{cookiecutter.docker_database_image}}
      POSTGRES_DB: {{cookiecutter.assembly_name}}-container
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{cookiecutter.database}}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: src/{{cookiecutter.assembly_name}}.Migrations/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      Postgresql__ConnectionString: Host=db;Database={{cookiecutter.assembly_name}}-container;User Id=postgres;Password=postgres

  {{cookiecutter.assembly_name|lower}}:
    image: ${DOCKER_REGISTRY-}{{cookiecutter.assembly_name|lower}}
    container_name: {{cookiecutter.assembly_name|lower}}
    hostname: {{cookiecutter.assembly_name|lower}}
    build:
      context: .
      dockerfile: src/{{cookiecutter.assembly_name}}/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      Postgresql__ConnectionString: Host=db;Database={{cookiecutter.assembly_name|lower}}-container;User Id=postgres;Password=postgres

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: storage
    hostname: azurite
    restart: always
    ports:
      - "10000:10000" 
      - "10001:10001"
      - "10002:10002"